FROM node:18-alpine3.16

# RUN mkdir -p /workspace/frontend/my-app && \
#     chown -R node:node /workspace/frontend/my-app
# WORKDIR /workspace/frontend/my-app
WORKDIR /workspace

# USER node

# COPY --chown=node:node my-app/package.json my-app/yarn.lock ./

# RUN yarn install

# COPY --chown=node:node . .